on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build esta porra
        run: |
          echo "Ok estou buildando"
          echo "Pronto ja buildei"
